{
    'name': 'Van Sales — Dori Savdosi Tizimi',
    'version': '1.0',
    'category': 'Sales/Point of Sale',
    'summary': 'Agentlar mashinasi savdosi, nasiya boshqaruvi va moliyaviy dashboard',
    'author': '',
    'depends': [
        'base',
        'mail',
        'account',
        'stock',
        'product',
        'uom',
        'point_of_sale',
    ],
    'data': [
        'security/van_sales_security.xml',
        'security/ir.model.access.csv',
        'data/van_sales_data.xml',
        'data/pos_payment_data.xml',
        'views/van_trip_views.xml',
        'views/van_sale_order_views.xml',
        'views/agent_views.xml',
        'views/pos_order_overrides.xml',
        'views/van_customer_views.xml',
        'views/van_nasiya_views.xml',
        'views/van_payment_views.xml',
        'views/menu_views.xml',
        'views/van_dashboard_views.xml',
        'views/van_dashboard_detail_views.xml',
        'views/van_pos_order_views.xml',
        'views/van_mobile_pos_action.xml',
        'report/van_load_act_report.xml',
        'report/van_trip_report.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'van_sales_pharma/static/src/css/van_sales.css',
            'van_sales_pharma/static/src/js/van_dashboard.js',
            'van_sales_pharma/static/src/xml/van_dashboard.xml',
            'van_sales_pharma/static/src/js/van_mobile_pos.js',
            'van_sales_pharma/static/src/xml/van_mobile_pos.xml',
        ],
        'point_of_sale._assets_pos': [
            'van_sales_pharma/static/src/js/cash_move_popup_override.js',
            'van_sales_pharma/static/src/xml/cash_move_popup_override.xml',
            'van_sales_pharma/static/src/xml/material_request_popup.xml',
            'van_sales_pharma/static/src/xml/navbar_override.xml',
            'van_sales_pharma/static/src/xml/product_info_popup_override.xml',
            'van_sales_pharma/static/src/js/material_request_popup.js',
            'van_sales_pharma/static/src/js/navbar_material_request.js',
            'van_sales_pharma/static/src/js/product_template_patch.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
